### ISSUE TITLE
Daily emails aren't sent

### ISSUE THREAD

**Issue by jacoballred** [einaregilsson/MyLife#9]
I have two MyLife apps. Both are running the latest version. Both mysteriously stopped sending the daily emails a few days ago. The last email I received for either app was 2/8, which makes me think something changed on Google's end maybe?

According to the log in the Google Developers Console, the emails are being successfully sent. One app sends old posts, one doesn't.

I've triple checked my spam folders. The emails are being sent to Gmail addresses for both apps.

Anyone else having this issue?

**Comment by einaregilsson** [comment]
I'm having this issue, last email sent on 2/7 for me. Logs say the mail was sent, it shows up in the quota page, but I get no email, and it's definitely not in spam.

I'll try tomorrow to add some test page and try different ways of sending email, but I really don't see why this would stop working all of a sudden. Do you have a non-gmail account that you could try sending to? Just trying to eliminate the possibility that there's something wrong there (although there shouldn't be)

**Comment by einaregilsson** [comment]
Well, after a lot of trial and error I figured out that the urls ("Past Entries") in the daily emails were causing App Engine to silently discard them. Must be some kind of spam prevention on their part. Kind of sucks since each MyLife instance only sends out one email but whatever. I removed the links and now it works fine. 

I've created a release with this + one bugfix I got a couple of days ago, it's at: https://github.com/einaregilsson/MyLife/releases/tag/1.2.3
